import { ReportColumnDefinition, ReportMetadataHeader } from '../dto/ExportDTO';

export class ExcelGenerationService {
  /**
   * Sanitizes values to prevent Anti-CSV Formula Injection attacks.
   */
  private static sanitizeCell(val: any): string {
    if (val === undefined || val === null) return '';
    const str = String(val).trim();
    if (/^[=+\-@\t\r]/.test(str)) {
      return `'${str}`;
    }
    return str;
  }

  /**
   * Generates Base64 encoded CSV payload with Metadata Header.
   */
  public static generateCsvPayload(
    headerMeta: ReportMetadataHeader,
    columns: ReportColumnDefinition[],
    dataRows: Record<string, any>[]
  ): string {
    let content = '';

    // 1. Report Metadata Header Section
    content += `# REPORT METADATA HEADER\n`;
    content += `# Report Title: "${headerMeta.reportTitle}"\n`;
    content += `# Generated At: "${headerMeta.generatedAt}"\n`;
    content += `# Generated By: "${headerMeta.generatedBy}" (Role: ${headerMeta.userRole})\n`;
    content += `# Filter Summary: "${headerMeta.filterSummary}"\n`;
    content += `# Total Records: ${headerMeta.totalRowsCount}\n`;
    content += `#\n`;

    // 2. Column Headers
    const headersLine = columns.map((c) => `"${c.headerName}"`).join(',');
    content += `${headersLine}\n`;

    // 3. Data Rows with Anti-CSV Formula Injection
    dataRows.forEach((row) => {
      const line = columns
        .map((c) => {
          const rawVal = row[c.fieldKey];
          // Guarantee NO sensitive hashes or Drive IDs
          if (c.fieldKey.includes('Password') || c.fieldKey.includes('Salt') || c.fieldKey.includes('DriveFileID')) {
            return '""';
          }
          const sanitized = this.sanitizeCell(rawVal);
          return `"${sanitized.replace(/"/g, '""')}"`;
        })
        .join(',');
      content += `${line}\n`;
    });

    return Utilities.base64Encode(Utilities.newBlob(content).getBytes());
  }
}
